// <auto-generated />
using System;
using DVDCollectRAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DVDCollectRAPI.Migrations
{
    [DbContext(typeof(DvdDbContext))]
    [Migration("20260723092323_AddTmdbAndAppSettings")]
    partial class AddTmdbAndAppSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("DVDCollectRAPI.Data.AppSettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("DVDCollectRAPI.Data.DvdEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Actors")
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioTracks")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaseType")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CollectionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryOfOrigin")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DiscCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastEdited")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaTypes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductionYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PurchasePlace")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PurchasePrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RatingAge")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RatingDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("RatingSystem")
                        .HasColumnType("TEXT");

                    b.Property<string>("Regions")
                        .HasColumnType("TEXT");

                    b.Property<string>("Released")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RunningTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SortTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Studios")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtitles")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UPC")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("WishPriority")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("DVDs");
                });

            modelBuilder.Entity("DVDCollectRAPI.Data.GenreEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("DVDCollectRAPI.Data.TmdbEntity", b =>
                {
                    b.Property<int>("DvdId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterPath")
                        .HasColumnType("TEXT");

                    b.Property<double?>("VoteAverage")
                        .HasColumnType("REAL");

                    b.Property<int?>("VoteCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("DvdId");

                    b.ToTable("Tmdb");
                });

            modelBuilder.Entity("DvdEntityGenreEntity", b =>
                {
                    b.Property<int>("DVDsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenresId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DVDsId", "GenresId");

                    b.HasIndex("GenresId");

                    b.ToTable("DVDGenres", (string)null);
                });

            modelBuilder.Entity("DVDCollectRAPI.Data.TmdbEntity", b =>
                {
                    b.HasOne("DVDCollectRAPI.Data.DvdEntity", "Dvd")
                        .WithOne("Tmdb")
                        .HasForeignKey("DVDCollectRAPI.Data.TmdbEntity", "DvdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dvd");
                });

            modelBuilder.Entity("DvdEntityGenreEntity", b =>
                {
                    b.HasOne("DVDCollectRAPI.Data.DvdEntity", null)
                        .WithMany()
                        .HasForeignKey("DVDsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DVDCollectRAPI.Data.GenreEntity", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DVDCollectRAPI.Data.DvdEntity", b =>
                {
                    b.Navigation("Tmdb");
                });
#pragma warning restore 612, 618
        }
    }
}
